version: "3.7"

services:

  minio1:
    build:
      context: .
    volumes:
      - data:/data
    ports:
      - "9001:9000"
    #network_mode: "host"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data:
